### ISSUE TITLE
User Story (Assessor) LO1: 1.3 build database-backed MVC web app

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#15]
EPIC: Use an Agile methodology to plan and design a Full-Stack Web application using an MVC framework and related contemporary technologies

As an assessor I can verify the use of **a database-backed MVC web application that allows users to store and manipulate data records about a particular domain** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

 * Acceptance Criteria 1: Create a database-backed MCV web app

 * Acceptance Criteria 2: Show users can store data records about a particular domain

 * Acceptance Criteria 3: Show users can manipulate data records about a particular domain

**Tasks**

- [ ] Create a database-backed MCV web app

- [ ] Show users can store data records about a particular domain

- [ ] Show users can manipulate data records about a particular domain
