### ISSUE TITLE
User Story (Assessor) LO1: 1.7

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#19]
EPIC: Use an Agile methodology to plan and design a Full-Stack Web application using an MVC framework and related contemporary technologies

As an assessor I can verify the use of ** Python code that is consistent in style and conforms to the PEP8 style guide and validated HTML and CSS code** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

* Acceptance Criteria 1:  PEP8 docs for python

 * Acceptance Criteria 2: W3C docs for HTML

 * Acceptance Criteria 3: W3C docs for CSS

**Tasks**

- [ ]  PEP8 docs for python 

- [ ]  W3C docs for HTML

- [ ] W3C docs for CSS
