### ISSUE TITLE
User Story (Assessor) LO1: 1.13 Doc UX design work

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#25]
EPIC: Use an Agile methodology to plan and design a Full-Stack Web application using an MVC framework and related contemporary technologies

As an assessor I can verify the use of **documentation of the UX design work undertaken for this project, including any wireframes, mockups, diagrams, etc.,created as part of the design process and its reasoning. Include diagrams created as part of the design process and demonstrate that these have been followed through to implementation** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

- [ ] * Acceptance Criteria 1: Show wireframes

- [ ] * Acceptance Criteria 2: workflows

- [ ] * Acceptance Criteria 3: demonstrate there continual use through displaying updated versions

**Tasks**

- [ ] * Task 1: 

- [ ] * Task 2: 

- [ ] * Task 3:
