### ISSUE TITLE
User Story (Assessor) L02: 2.2 Functionality for users

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#26]
EPIC: Implement a data model, application features and business logic to manage, query and manipulate data to meet given needs in a particular real-world domain

As an assessor I can verify the use of ** functionality for users to create, locate, display, edit and delete records** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

- [ ] * Acceptance Criteria 1:  User can create records

- [ ] * Acceptance Criteria 2: User can locate records

- [ ] * Acceptance Criteria 3: User can display records

- [ ] * Acceptance Criteria 4: User can edit records

- [ ] * Acceptance Criteria 5: User can delete records

**Tasks**

- [x] Task 1:  User can create records

- [x] Task 2: User can locate records

- [x] Task 3: User can display records

- [x] Task 4: User can edit records

- [x] Task 5: User can delete records
