### ISSUE TITLE
User Story (Assessor) L02: 2.4

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#28]
EPIC: Implement a data model, application features and business logic to manage, query and manipulate data to meet given needs in a particular real-world domain

As an assessor I can verify the use of **Implementing at least one form, with validation, that allows users to create and edit models in the backend** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

 * Acceptance Criteria 1:  Implentation of a form with validation

 * Acceptance Criteria 2: User can create a model in backend

* Acceptance Criteria 3: User can delete a model in backend

**Tasks**

- [ ] Implentation of a form with validation 

- [x] User can create a model in backend 

- [x] User can delete a model in backend
