### ISSUE TITLE
User Stories (Assessor) L04: 4.1 Manual testing

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#32]
EPIC: Create manual and/or automated tests for a Full-Stack Web application using an MVC framework and related contemporary technologies

As an assessor I can verify the use of **manual and/or automated Python test procedures to assess functionality,
usability, responsiveness and data management within the entire web application** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

 * Acceptance Criteria 1:  manual testing to assess functionality

* Acceptance Criteria 2: manual testing to assess accessability

* Acceptance Criteria 3:  manual testing to assess usability

* Acceptance Criteria 4:  manual testing to assess responsiveness

 * Acceptance Criteria 5:  manual testing to assess data management

**Tasks**

- [ ] manual testing to assess functionality

- [ ] manual testing to assess accessibility

- [ ] manual testing to assess usability
- [ ]  manual testing to assess responsiveness
- [ ]  manual testing to assess data management
