### ISSUE TITLE
User Stories (Assessor) L04: 4.2

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#33]
EPIC: Create manual and/or automated tests for a Full-Stack Web application using an MVC framework and related contemporary technologies

As an assessor I can verify the use of **manual and/or automated JavaScript test procedures to assess functionality,
usability, responsiveness and data management within the entire web application** so that a pass grade may be awarded.

 **Acceptance Criteria:** 

* Acceptance Criteria 1:  manual test to assess JS functionality

* Acceptance Criteria 2: manual test to assess JS usability

* Acceptance Criteria 3: manual test to assess JS responsiveness

* Acceptance Criteria 4: manual test to assess JS data management

**Tasks**

- [ ] manual test to assess JS functionality
- [ ] manual test to assess JS usability
- [ ] manual test to assess JS responsiveness
- [ ] manual test to assess JS data management
- [ ] bug: jest not work on jquery
