### ISSUE TITLE
USER STORY: Header Website Navigation

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#4]
EPIC: Navigate Website

As a customer, I can easily move through the website so I can gather more information on certain aspects

**Acceptance Criteria:**

Acceptance Criteria 1: Working anchor links in header 

Acceptance Criteria 2: Dropdown toggle menu for mobile screensizes

Acceptance Criteria 3: All information on one page

**Tasks**

- [ ] Task 1: Create responsive header with anchor links

- [x] Task 2: Create dropdown toggle option for mobile

- [ ] Task 3: Have all information one page using appropriate HTML/CSS/Bootstrap
