### ISSUE TITLE
USER STORY: Footer Navigation

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#5]
EPIC: Navigate Nags With Notions Content

As a customer, I can easily click on a link to Nags with Notions other social media accounts, I can also find contact information easily. These options are at the bottom of every page.

**Acceptance Criteria:**

- [ ] Acceptance Criteria 1: Links to FB, Insta, LinkedIn & Github in footer using icons

- [ ] Acceptance Criteria 2: Owners contact details in the footer

**Tasks**

- [ ] Task 1: Use icons to create links in footer to other media accounts

- [ ] Task 2: Separate footer into colums & add content to second column
