### ISSUE TITLE
USER STORY: LO2 Implement a data model

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#8]
EPIC: Data Model Implementation

As an assessor I can verify the use of a data model, application features and business logic to manage, query and manipulate data to meet given needs in a particular real-world domain so that a pass grade may be awarded

- [ ] **Acceptance Criteria:** Show use of a data model

- [ ] * Acceptance Criteria 1: Show use of data manipulation to meet a consumer need

**Tasks**

- [ ] * Task 1: Implement a functional data model

- [ ] * Task 2: Show data manipulation to meet a consumer need

- [ ] * Task 3:
