### ISSUE TITLE
User Story (Assessor): LO3 Authorisation features

### ISSUE THREAD

**Issue by JWalshe86** [JWalshe86/Nags-With-Notions2.0#9]
EPIC: Apply authorization, authentication, and permission features in a Full-Stack web application solution

As an assessor I can verify the use of **authorisation, authentication and permission features in a Full-Stack web application solution** so that a pass grade may be awarded.

 **Acceptance Criteria:**

- [ ] * Acceptance Criteria 1:  Functioning authorisation processes present in project 

- [ ] * Acceptance Criteria 2: Authentication features present in project

- [ ] * Acceptance Criteria 3: Permission Features Present in project

**Tasks**

- [ ] * Task 1: 

- [ ] * Task 2: 

- [ ] * Task 3:
